apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapi-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: pythonapi 
        image: udiscopotato/pythonapi
        ports:
        - containerPort: 7000

---
apiVersion: v1
kind: Service
metadata:
  name: pythonapi-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30002

